// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szvmdnxdyvunaktqpfxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6dm1kbnhkeXZ1bmFrdHFwZnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTgwNzYsImV4cCI6MjA2Njg3NDA3Nn0.iojInouv6kZ39NiUjO1zPR5bfnIHghLtPStAGATD_0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});